name: CRON Schedule for keeping api service awake

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  cron:
    name: "Ping api service"
    runs-on: ubuntu-latest
    steps:
      - name: Ping service
        run: |
          curl --request GET \
            --url 'https://codetips-cms.onrender.com/api/Projects'
